name: Secret Manager Trigger
on:
  workflow_dispatch:
    inputs:
      secrets_generic:
        description: 'JSON containing key value pairs for generic secrets'
        required: false
        type: string
        default: ''
      secrets_files:
        description: 'JSON containing key value pairs for base64 encoded secret files'
        required: false
        type: string
        default: ''
      release_name:
        description: 'Helm release name for the deployment. This uniquely identifies one deployment instance of the application.'
        type: string
        required: true
      app_namespace:
        description: 'Kubernetes namespace for the deployment. Same thing as release_name in most cases when deploying microservices'
        type: string
        required: true
      environment:
        description: 'Environment for secret'
        required: true
        default: 'uat'
        type: choice
        options:
          - uat
          - prod
          - dev
          - qa

jobs:
  create-secrets:
    uses: Plural-Pvt/Plural_Ops/.github/workflows/common-secret-manager.yaml@main
    with:
      SECRETS_GENERIC: ${{ toJson(inputs.secrets_generic) }}
      SECRETS_FILES: ${{ toJson(inputs.secrets_files) }}
      APP_NAMESPACE: ${{ inputs.app_namespace }}
      RELEASE_NAME: ${{ inputs.release_name}}
      ENV: ${{ inputs.environment }}